---
- name: Install Redis
  apt:
    name:
      - redis-server
    state: latest

- name: Configure Redis to listen on all interfaces
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind '
    line: 'bind 0.0.0.0'
  notify:
    - Restart redis-server

- name: Set Redis password
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^#?\s*requirepass '
    line: "requirepass {{ redis_password }}"
  no_log: true
  notify:
    - Restart redis-server
