---
- name: Provision all services
  hosts:
    - my_vm
  gather_facts: false
  become: true
  roles:
    - { role: mariaDB, tags: ['mariadb'] }
    - { role: redis, tags: ['redis'] }
    - { role: rabbitmq, tags: ['rabbitmq'] }
    - { role: elasticsearch, tags: ['elasticsearch'] }
    - { role: node_exporter, tags: ['node_exporter', 'observability'] }
    - { role: prometheus, tags: ['prometheus', 'observability'] }
    - { role: grafana, tags: ['grafana', 'observability'] }
