---
- name: Install rabbitmq
  become: true
  script: ./files/rabbitmq.sh

- name: Enable the rabbitmq_management plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled

- name: Adding user with full access control on / vhost
  rabbitmq_user:
    user: "{{ rabbitmq_admin_user }}"
    password: "{{ rabbitmq_admin_password }}"
    tags: administrator
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
  no_log: true

- name: Ensure that the test vhost exists
  rabbitmq_vhost:
    name: "{{ rabbitmq_test_vhost }}"
    state: present
