---
- name: Installing Elastic Search
  script: ./files/installES.sh

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable Elasticsearch service
  systemd:
    name: elasticsearch.service
    enabled: yes

- name: Start Elasticsearch service
  systemd:
    name: elasticsearch.service
    state: started

- name: Update the network address
  ansible.builtin.lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^#network.host'
    line: 'network.host: 0.0.0.0'

- name: Add the discovery.type line
  ansible.builtin.lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    insertafter: '^#?discovery\.seed_hosts:'
    line: 'discovery.type: single-node'
  notify:
    - Restart elasticsearch
